export const allProjects = [
  {
    id: 1,
    title: 'Transfinance Mobile Approval',
    subtitle: 'Enterprise Digital Approval App',
    description: 'Flutter app and Express.js gateway securing cash advances and document signing via a hybrid RSA+AES cryptosystem.',
    fullDesc: 'An enterprise-grade digital approval mobile application developed for PT Transpacific Finance. It enables paperless approval workflows, cash advance (Kasbon) requests, and FPPU document signing. High-risk financial payloads are secured over public networks using a hybrid RSA-2048 and AES-128-CBC encryption model.',
    features: [
      'RSA-2048 + AES-128-CBC hybrid encryption model for secure payload transit',
      'Clean MVVM client architecture built with Flutter, Provider, and GetIt',
      'Digital signature pad integration for direct document approval signing',
      'Firebase Cloud Messaging (FCM) for real-time pending approval notifications',
      'Secure Node.js & Express API gateway coordinating requests to the enterprise backend',
      'Robust offline preference caching with Shared Preferences'
    ],
    image: '/projects/mobile-approval.png',
    tags: ['Flutter', 'Dart', 'Node.js', 'Express.js', 'MySQL', 'Cryptography'],
    demo: null,
    github: null,
    featured: true,
  },
  {
    id: 2,
    title: 'WBS',
    subtitle: 'Whistleblowing System',
    description: 'Two-sided anonymous misconduct reporting and tracking platform with secure admin dashboard.',
    fullDesc: 'A two-sided Whistleblowing System (WBS) enabling public users to submit anonymous misconduct reports and securely track progress via unique tracking codes. Built with an admin dashboard to process reports through verification stages and interact with reporters via a secure, anonymous message thread.',
    features: [
      'Anonymous report submission & progress tracking via unique tracking codes',
      'Interactive admin dashboard for report management and lifecycle updates',
      'Secure chat thread for real-time, anonymous communication between admin and reporter',
      'Support for secure file evidence uploads',
      'Client compiled to a single, self-contained HTML file (using vite-plugin-singlefile) for easy deployment'
    ],
    image: null,
    tags: ['React', 'Express.js', 'Prisma', 'PostgreSQL', 'TypeScript', 'Tailwind CSS'],
    demo: null,
    github: null,
    featured: false,
  },
  {
    id: 3,
    title: 'Hyve',
    subtitle: 'Note-Taking App',
    description: 'MERN-based note-taking app with gamification and OAuth login for collaborative academic use.',
    fullDesc: 'Hyve reimagines collaborative note-taking for students. Built on the MERN stack with real-time sync, gamification layers that reward consistent study habits, and OAuth for frictionless onboarding. Designed for speed and reliability under concurrent user load.',
    features: ['Real-time collaborative editing', 'OAuth 2.0 login (Google)', 'Gamification & streak system', 'Responsive mobile-first UI', 'RESTful API with JWT auth'],
    image: '/projects/Hyve.webp',
    tags: ['React', 'Express.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    demo: 'https://hyveapp.netlify.app/',
    github: 'https://github.com/Axeldarren/Hyve-Notes-App',
    featured: false,
  },
  {
    id: 4,
    title: 'ITList',
    subtitle: 'Project Management App',
    description: 'Full-stack PM app centralizing project tracking, time management, and reporting for internal IT teams.',
    fullDesc: 'Enterprise-grade project management platform built for internal IT operations. Centralizes task tracking, sprint planning, time logging, and automated reporting in a single unified dashboard.',
    features: ['Real-time WebSocket updates', 'Role-based access control', 'Sprint planning & burndown charts', 'Time tracking & reports', 'Automated PDF/Excel reporting'],
    image: '/projects/ITList.webp',
    tags: ['Next.js', 'MySQL', 'Prisma', 'WebSockets', 'Express.js'],
    demo: null,
    github: 'https://github.com/Axeldarren/itlist',
    featured: true,
  },
  {
    id: 5,
    title: 'PRDify',
    subtitle: 'AI PRD Automation',
    description: 'Automates Product Requirement Document creation using LLMs for intelligent content generation.',
    fullDesc: 'PRDify leverages large language models to dramatically accelerate product discovery. PMs input a brief problem statement and PRDify generates structured PRDs — cutting doc creation time by 80%.',
    features: ['LLM-powered PRD generation', 'Structured output templates', 'Acceptance criteria automation', 'Export to PDF & Notion', 'Team collaboration mode'],
    image: '/projects/PRDify.webp',
    tags: ['Next.js', 'LLM', 'AI', 'Automation', 'Google Cloud'],
    demo: null,
    github: 'https://github.com/C242-PM02-TEAM',
    featured: true,
  },
  {
    id: 6,
    title: 'GenLingo',
    subtitle: 'AI Slang Learning Platform',
    description: 'Interactive platform using Llama 3.3 to teach Gen Z & Gen Alpha slang through AI chatbots, quizzes, and a Duolingo-style learning path.',
    fullDesc: 'GenLingo bridges generational language gaps by teaching Gen Z and Gen Alpha slang through AI-powered persona chatbots, spaced-repetition pop quizzes, a searchable slang encyclopedia, and a Duolingo-style learning path with XP, levels, and progressive unit unlocking.',
    features: ['Llama 3.3 70B via Groq', 'Dual AI personas (Gen Z & Gen Alpha)', 'Spaced repetition pop quizzes', 'Duolingo-style learning path with XP', 'Slang encyclopedia with 230+ terms', 'Streamed chat responses', 'Deployed on Streamlit Cloud'],
    image: '/projects/Genlingo.webp',
    tags: ['Python', 'Streamlit', 'AI', 'Groq', 'NLP'],
    demo: 'https://genlingo.streamlit.app/',
    github: 'https://github.com/Axeldarren/GenLingo',
    featured: true,
  },
  {
    id: 7,
    title: 'Skin Cancer Detection',
    subtitle: 'ML on GCP',
    description: 'Backend for skin cancer detection using ML on Compute Engine and Firestore, via secure GCP REST API.',
    fullDesc: 'Cloud-native ML backend classifying skin lesion images using a trained CNN hosted on GCP Compute Engine. Medical-grade preprocessing, Firestore persistence, and a secure REST API for mobile client integration.',
    features: ['CNN-based image classification', 'GCP Compute Engine hosting', 'Firestore result storage', 'Secure REST API', 'HAPI.js server framework'],
    image: '/projects/SkinCancer.webp',
    tags: ['Machine Learning', 'GCP', 'Node.js', 'HAPI.js'],
    demo: null,
    github: 'https://github.com/Axeldarren/Skin_Cancer_Detection_App',
    featured: false,
  },
  {
    id: 8,
    title: 'Password Manager',
    subtitle: 'C++ / DSA',
    description: 'C++ password manager using linked lists and encryption secured with a master password.',
    fullDesc: 'From-scratch C++ password manager demonstrating advanced data structures and applied cryptography. Credentials stored in a doubly-linked list, encrypted with a symmetric cipher, gated behind a hashed master password.',
    features: ['Doubly-linked list storage', 'Symmetric encryption', 'Master password hashing', 'CRUD credential management', 'CSV export / import'],
    image: '/projects/Password.webp',
    tags: ['C++', 'Data Structures', 'Encryption'],
    demo: null,
    github: 'https://github.com/Axeldarren/Password-Manager-Project-DSA-Repositories',
    featured: false,
  },
  {
    id: 9,
    title: 'TEDx Sampoerna University Website',
    subtitle: 'Event Landing Page',
    description: 'Designed and developed the official TEDx event website using WordPress, featuring schedules and registration.',
    fullDesc: 'Designed and built the official landing page for TEDx Sampoerna University during Google Developer Student Club (GDSC) lead tenure. Developed using WordPress with a focus on brand guidelines and high-traffic stability, featuring interactive event schedules, speaker profile grids, and seamless registration pipelines.',
    features: [
      'Custom theme design and development aligned with TEDx guidelines',
      'Interactive speaker profile grids and dynamic event schedule timelines',
      'Seamless ticket booking integration and attendee registration flow',
      'Performance caching and CDN configuration for stability under load',
      'Fully responsive mobile layouts for social media traffic'
    ],
    image: '/projects/tedx.png',
    tags: ['WordPress', 'PHP', 'UI/UX', 'GDSC', 'Event Management'],
    demo: null,
    github: null,
    featured: false,
  },
];

export const experiences = [
  {
    id: 1,
    company: 'PT Transpacific Finance',
    location: 'Jakarta, ID',
    period: 'Sep 2025 – May 2026',
    role: 'Mobile Developer Intern',
    type: 'engineering',
    current: false,
    about: 'Indonesian multi-purpose financing and fund facilities provider.',
    bullets: [
      'Engineered a production-grade procurement app published on Google Play Store & Apple App Store, serving 40+ internal users.',
      'Independently designed and built 15+ RESTful APIs handling procurement submission, approval workflows, and data management.',
      'Contributed to Flutter frontend, integrating APIs and state management for smooth cross-platform UX.',
    ],
  },
  {
    id: 2,
    company: 'Skilio',
    location: 'Singapore',
    period: 'Sep 2025 – Oct 2025',
    role: 'Quality Assurance Engineer Intern',
    type: 'qa',
    about: 'SEA-based talent platform connecting Gen Z professionals through skills-first hiring.',
    bullets: [
      'Executed 50+ UAT cases across mobile and web, validating core features against business requirements.',
      'Identified, documented and reported 10+ functional and usability defects with clear reproduction steps.',
      'Performed regression testing to verify bug fixes and ensure pre-release stability.',
      'Collaborated with product and engineering teams to improve release readiness.',
    ],
  },
  {
    id: 3,
    company: 'PT Transpacific Finance',
    location: 'Jakarta, ID',
    period: 'Jun 2025 – Sep 2025',
    role: 'Software Engineer Intern',
    type: 'engineering',
    about: 'Indonesian multi-purpose financing and fund facilities provider.',
    bullets: [
      'Engineered a full-stack project management system (Next.js, Express.js, MySQL) owning the full dev lifecycle.',
      'Implemented real-time time tracking and task management for 15+ internal users.',
      'Built automated reporting modules generating PDF and Excel reports.',
      'Integrated WebSocket real-time updates and deployed on internal servers.',
    ],
  },
  {
    id: 4,
    company: 'Bangkit Academy Led by Google, Tokopedia, Gojek & Traveloka',
    location: 'Jakarta, ID',
    period: 'Sep 2024 – Jan 2025',
    role: 'Cloud Engineer Intern',
    type: 'cloud',
    about: 'Bangkit Academy, led by Google, Tokopedia, Gojek & Traveloka — develops top tech talent for Indonesia.',
    bullets: [
      'Selected for Company Capstone Track, leading a team of 4 to develop PRDify using LLMs and Google Cloud.',
      'Designed microservice architecture: Next.js frontend + Express.js backend on Cloud Run, GCS, and SQL.',
      'Integrated LLM pipelines on Compute Engine with OpenAPI, Claude API, LangChain & prompt engineering.',
      'Completed 32 specialized courses covering Cloud Computing, Kubernetes, DevOps, and Applied ML.',
    ],
  },
  {
    id: 5,
    company: 'PT Salam Pacific Indonesia Lines',
    location: 'Jakarta, ID',
    period: 'Jul 2024 – Aug 2024',
    role: 'AI Engineer Intern — Team Leader',
    type: 'ai',
    about: 'Leading container liner company in Indonesia.',
    bullets: [
      'Developed a chatbot using prompt engineering for large-scale data processing with Groq API and Gemini.',
      'Led development of an AI chatbot automating incident reporting and analysis.',
      'Led creation of an ANN-based ML model for recruitment recommendations.',
      'Led an AI-driven WhatsApp chatbot on GCP and Vertex AI for recruitment communications.',
    ],
  },
  {
    id: 6,
    company: 'Connextion Indonesia',
    location: 'Jakarta, ID',
    period: 'May 2024 – Nov 2024',
    role: 'Project Manager Intern',
    type: 'management',
    about: 'Emerging IT community helping members gain experience for tech project portfolios.',
    bullets: [
      'Led the "Super Project," managing 10+ participants and delivering 2 portfolio-ready tech projects on time.',
      'Implemented project timelines and task delegation strategies, increasing efficiency by 20%.',
      'Organized and facilitated 5 webinars on Product Management, UI/UX, and Engineering for 30+ participants.',
    ],
  },
  {
    id: 7,
    company: 'Google Developer Student Club',
    location: 'Jakarta, ID',
    period: 'May 2024 – Aug 2024',
    role: 'Core Team Member — WordPress Dev Lead',
    type: 'management',
    about: 'University club helping students learn and apply Google technologies.',
    bullets: [
      'Co-led a team of 14 (frontend engineers + UI/UX designers) to develop the BEM KM FOB Sampoerna University website.',
      'Utilized Figma for design and WordPress for development, ensuring seamless UX and on-time delivery.',
    ],
  },
  {
    id: 8,
    company: 'PT Salam Pacific Indonesia Lines',
    location: 'Jakarta, ID',
    period: 'May 2024 – Jun 2024',
    role: 'Software Developer Intern — Team Leader',
    type: 'engineering',
    about: 'Leading container liner company in Indonesia.',
    bullets: [
      'Led 5 interns to deliver a full web application in under 2 months.',
      'Developed a comprehensive driver recruitment system.',
      'Designed the database from scratch using Google Cloud Platform.',
      'Produced two sites: an admin dashboard and a driver applicant portal.',
    ],
  },
];

export const typeColors = {
  engineering: 'var(--accent)',
  cloud: 'oklch(0.6 0.16 200)',
  ai: 'oklch(0.6 0.16 280)',
  management: 'oklch(0.6 0.16 140)',
  qa: 'oklch(0.6 0.16 60)',
};

export const typeLabels = {
  engineering: 'Engineering',
  cloud: 'Cloud',
  ai: 'AI/ML',
  management: 'Management',
  qa: 'QA',
};
